(function(){const ONE_TAP_BLOCKED_COOKIE="_ezgoogleOneTapBlocked";function setCookie(name,value,maxAgeSeconds){let cookie=name+"="+value+"; path=/";if(maxAgeSeconds!=null)cookie+="; max-age="+maxAgeSeconds;document.cookie=cookie;}
function validateEmail(email){if(!email)return false;var emailParts=email.split('@');if(emailParts.length!==2)return false;var account=emailParts[0];var address=emailParts[1];if(account.length>64)return false;else if(address.length>255)return false;var domainParts=address.split('.');if(domainParts.some(function(part){return part.length>63;}))return false;var tester=/^[-!#$%&'*+\/0-9=?A-Z^_a-z`{|}~](\.?[-!#$%&'*+\/0-9=?A-Z^_a-z`{|}~])*@[a-zA-Z0-9](-*\.?[a-zA-Z0-9])*\.[a-zA-Z](-?[a-zA-Z0-9])+$/;return tester.test(email);}
function normalizeEmail(email){return email.toLowerCase().trim();}
function decodeJwtResponse(token){let base64Url=token.split('.')[1];let base64=base64Url.replace(/-/g,'+').replace(/_/g,'/');let jsonPayload=decodeURIComponent(atob(base64).split('').map(function(c){return '%'+('00'+c.charCodeAt(0).toString(16)).slice(-2);}).join(''));return JSON.parse(jsonPayload);}
function handleCredentialResponse(response){let profile=decodeJwtResponse(response.credential);try{let email=normalizeAndValidateEmail(profile.email);window.ezoicIdentity=window.ezoicIdentity||{};window.ezoicIdentity.queue=window.ezoicIdentity.queue||[];window.ezoicIdentity.queue.push(function(){window.ezoicIdentity.setIdentityFromSource({email:email},"googleOneTap");});window.dispatchEvent(new CustomEvent('googleOneTap:credential',{detail:{credential:response.credential,select_by:response.select_by},bubbles:false,composed:false}));}catch(e){console.error(e);}}
function normalizeAndValidateEmail(email){email=normalizeEmail(email);if(validateEmail(email))return email;throw new Error('Email invalid');}
function waitForEzoicIdentity(){return new Promise((resolve)=>{const checkIdentity=()=>{if(typeof window.ezoicIdentity!=='undefined'&&typeof window.ezoicIdentity.getUID==='function'){resolve();}else{setTimeout(checkIdentity,100);}};checkIdentity();});}
function sendCustomPageviewEvent(key,value,maxRetries=50,intervalMs=100){return new Promise((resolve,reject)=>{let attempts=0;const isReady=()=>typeof window._ezaq?.page_view_id!=="undefined"&&typeof window.__ez?.ce?.AddPageviewEvent==="function";const poll=()=>{if(isReady()){try{window.__ez.ce.AddPageviewEvent(key,value);resolve();}catch(err){reject(err);}
return;}
if(attempts>=maxRetries){reject(new Error("sendCustomPageviewEvent: max retries reached"));return;}
attempts++;setTimeout(poll,intervalMs);};poll();});}
function isConsentPopupComing(){return getCookie('ez-consent-tcf')==null;}
function getCookie(name){const nameEQ=name+"=";const ca=document.cookie.split(';');for(let i=0;i<ca.length;i++){let c=ca[i].trim();if(c.indexOf(nameEQ)===0)return c.substring(nameEQ.length,c.length);}
return null;}
async function initGoogleOneTap(){if(typeof window.ezGoogleOneTapInitialized!=='undefined'&&window.ezGoogleOneTapInitialized===true){console.log("Google One Tap already initialized - another file called it");return;}
await waitForEzoicIdentity();if(window.ezoicIdentity.getUID()!=null&&typeof window.ezoicIdentity.isInternalUIDSource==='function'&&window.ezoicIdentity.isInternalUIDSource()===true){console.log("Google One Tap already initialized - User Already Logged In");return;}
window.ezGoogleOneTapInitialized=true;if(getCookie(ONE_TAP_BLOCKED_COOKIE)!=null)return;if(!document.querySelector('script[data-ez-gsi]')&&!(window.google&&google.accounts&&google.accounts.id)){window.googleSignInScript=document.createElement('script');window.googleSignInScript.type='text/javascript';window.googleSignInScript.async=true;window.googleSignInScript.src='https://accounts.google.com/gsi/client';window.googleSignInScript.setAttribute('data-ez-gsi','1');var x=document.getElementsByTagName('script')[0]||document.head;x.parentNode.insertBefore(window.googleSignInScript,x);window.googleSignInScript.onload=onGsiReady;}else{onGsiReady();}
function onGsiReady(){const consentPopupComing=isConsentPopupComing();if(!window.google||!google.accounts||!google.accounts.id)return;google.accounts.id.initialize({client_id:window.__ezOneTapClientId,auto_select:true,button_auto_select:true,cancel_on_tap_outside:!consentPopupComing,context:'signin',ux_mode:'popup',itp_support:true,callback:handleCredentialResponse});google.accounts.id.prompt((notification)=>{if(notification.isNotDisplayed()||notification.isSkippedMoment()||notification.isDismissedMoment()){setCookie(ONE_TAP_BLOCKED_COOKIE,"true",24*60*60);}
if(!notification.isNotDisplayed()){sendCustomPageviewEvent('google_one_tap_prompt_displayed','true').catch((e)=>{console.error(e);});}});}}
window.ezgoogleOneTap={isPromptOn(){if(window.ezoicIdentity&&typeof window.ezoicIdentity.getUID==='function'&&window.ezoicIdentity.getUID()!=null&&typeof window.ezoicIdentity.isInternalUIDSource==='function'&&window.ezoicIdentity.isInternalUIDSource()===true){console.log("Google One Tap already initialized - User Already Logged In");return false;}
if(getCookie(ONE_TAP_BLOCKED_COOKIE)!=null)return false;return true;}};initGoogleOneTap();})();